package transporter;

import javax.swing.JOptionPane;

public class TelaCadastroCidadeX extends javax.swing.JInternalFrame {

    public TelaCadastroCidadeX() {
        initComponents();

        this.setTitle("Cadastro de Cidade");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastroCidade = new javax.swing.JPanel();
        lblCadastroCidadeCidade = new javax.swing.JLabel();
        lblCadastroCidadeEstado = new javax.swing.JLabel();
        lblCadastroCidadeCI = new javax.swing.JLabel();
        txtCadastroCidadeCidade = new javax.swing.JTextField();
        txtCadastroCidadeCI = new javax.swing.JTextField();
        txtCadastroCidadeEstado = new javax.swing.JTextField();
        btnCadastroCidadeSalvar = new javax.swing.JButton();
        btnCadastroCidadeCancelar = new javax.swing.JButton();
        lblCadastroCidades = new javax.swing.JLabel();

        setClosable(true);

        lblCadastroCidadeCidade.setText("Cidade");

        lblCadastroCidadeEstado.setText("Código Identificador");

        lblCadastroCidadeCI.setText("Estado");

        btnCadastroCidadeSalvar.setText("Salvar");
        btnCadastroCidadeSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroCidadeSalvarActionPerformed(evt);
            }
        });

        btnCadastroCidadeCancelar.setText("Cancelar");
        btnCadastroCidadeCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroCidadeCancelarActionPerformed(evt);
            }
        });

        lblCadastroCidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCadastroCidades.setText("Cadastro de Cidade");

        javax.swing.GroupLayout pnlCadastroCidadeLayout = new javax.swing.GroupLayout(pnlCadastroCidade);
        pnlCadastroCidade.setLayout(pnlCadastroCidadeLayout);
        pnlCadastroCidadeLayout.setHorizontalGroup(
            pnlCadastroCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroCidadeLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlCadastroCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadastroCidades)
                    .addGroup(pnlCadastroCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblCadastroCidadeCidade)
                        .addComponent(txtCadastroCidadeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroCidadeLayout.createSequentialGroup()
                            .addGroup(pnlCadastroCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCadastroCidadeCI)
                                .addComponent(txtCadastroCidadeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlCadastroCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCadastroCidadeEstado)
                                .addComponent(txtCadastroCidadeCI, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroCidadeLayout.createSequentialGroup()
                            .addComponent(btnCadastroCidadeSalvar)
                            .addGap(18, 18, 18)
                            .addComponent(btnCadastroCidadeCancelar))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlCadastroCidadeLayout.setVerticalGroup(
            pnlCadastroCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroCidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastroCidades)
                .addGap(13, 13, 13)
                .addComponent(lblCadastroCidadeCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCadastroCidadeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadastroCidadeEstado)
                    .addComponent(lblCadastroCidadeCI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadastroCidadeCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadastroCidadeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnlCadastroCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroCidadeCancelar)
                    .addComponent(btnCadastroCidadeSalvar))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadastroCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadastroCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroCidadeSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroCidadeSalvarActionPerformed
        String cidade = txtCadastroCidadeCidade.getText();
        String estado = txtCadastroCidadeEstado.getText();
        int codigo = Integer.parseInt(txtCadastroCidadeCI.getText());
        
        TelaPrincipal.cidades.add(
                new Cidade(cidade, estado, codigo)
        );
        
        JOptionPane.showMessageDialog(null, 
                "Cadastro realizado com sucesso!"
        );
        
        this.dispose();
    }//GEN-LAST:event_btnCadastroCidadeSalvarActionPerformed

    private void btnCadastroCidadeCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroCidadeCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCadastroCidadeCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroCidadeCancelar;
    private javax.swing.JButton btnCadastroCidadeSalvar;
    private javax.swing.JLabel lblCadastroCidadeCI;
    private javax.swing.JLabel lblCadastroCidadeCidade;
    private javax.swing.JLabel lblCadastroCidadeEstado;
    private javax.swing.JLabel lblCadastroCidades;
    private javax.swing.JPanel pnlCadastroCidade;
    private javax.swing.JTextField txtCadastroCidadeCI;
    private javax.swing.JTextField txtCadastroCidadeCidade;
    private javax.swing.JTextField txtCadastroCidadeEstado;
    // End of variables declaration//GEN-END:variables
}
