package transporter;

import javax.swing.table.DefaultTableModel;

public class TelaVisualizarPassagensX extends javax.swing.JInternalFrame {

    public TelaVisualizarPassagensX() {
        initComponents();
        
        this.setTitle("Visualizar Passagens");
        this.setResizable(false);
        
        DefaultTableModel tab = new DefaultTableModel();
        tab.addColumn("Cidade de origem");
        tab.addColumn("Cidade de destino");
        tab.addColumn("Data");
        tab.addColumn("Poltrona");
        tab.addColumn("Passageiro");
        tab.addColumn("CPF");
        
        for(Passagem p : TelaPrincipal.passagens) {
            tab.addRow(
                new Object [] { 
                    p.getCidadeOrigem(), p.getCidadeDestino(), p.getData(), p.getPoltrona(), p.getPassageiro(), p.getCpf()
                }
            );
        }
        
        tabListaPassageiros.setModel(tab);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabListaPassageiros = new javax.swing.JTable();
        lblListaPassagens = new javax.swing.JLabel();

        setClosable(true);

        tabListaPassageiros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabListaPassageiros);

        lblListaPassagens.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblListaPassagens.setText("Lista de Passagens");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblListaPassagens)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaPassagens)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListaPassagens;
    private javax.swing.JTable tabListaPassageiros;
    // End of variables declaration//GEN-END:variables
}
